import { Component, OnInit } from '@angular/core';
import { MaterialModule } from '../../models and helpers/material.module';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Task } from '../../models and helpers/task.model';
import { TaskService } from '../../models and helpers/task.service';
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';

@Component({
  selector: 'app-task-form',
  imports: [MaterialModule, ReactiveFormsModule,CommonModule],
  templateUrl: './task-form.component.html',
  styleUrl: './task-form.component.css',
  standalone:true
})
export class TaskFormComponent implements OnInit {
  taskForm!:FormGroup;

  constructor(private fb: FormBuilder, private taskService: TaskService) { }

  ngOnInit(): void {
    this.initializeForm()
  }

  initializeForm() {
    this.taskForm = this.fb.group({
      title: ['', Validators.required],
      description: [''],
      status: ['', Validators.required],
      dueDate: ['', Validators.required],
    });
  }




  onSubmit() {
    if (this.taskForm.valid) {
      const newTask: Task = {
        id: 0, // This will be auto-generated by the server
        title: this.taskForm.value.title!,
        description: this.taskForm.value.description!,
        status: this.taskForm.value.status! as 'Pending' | 'In Progress' | 'Completed',
        dueDate: this.taskForm.value.dueDate!,
      };

      this.taskService.addTask(newTask).subscribe(() => {
        this.taskService.fetchTasks();
        this.taskForm.reset();
      });
    }
  }
}
